test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.80bdea70.name = "Upgrade from 0.19~ynh1"
