#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

fpm_footprint="low"
fpm_free_footprint=0
fpm_usage="low"
ynh_app_setting_set --app="$app" --key=fpm_footprint --value="$fpm_footprint"
ynh_app_setting_set --app="$app" --key=fpm_free_footprint --value="$fpm_free_footprint"
ynh_app_setting_set --app="$app" --key=fpm_usage --value="$fpm_usage"

#=================================================
# CONFIGURING A POSTGRESQL DATABASE
#=================================================
ynh_script_progression --message="Configuring $app's PostgreSQL database..."

ynh_psql_execute_as_root --database="$db_name" --sql="CREATE EXTENSION IF NOT EXISTS unaccent;"
ynh_psql_execute_as_root --database="$db_name" --sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding $app's configuration file..."

ynh_add_config --template="db.example.inc.php" --destination="$install_dir/config/db.inc.php"

chmod 400 "$install_dir/config/db.inc.php"
chown "$app:$app" "$install_dir/config/db.inc.php"

#=================================================
# BUILD MOVIM
#=================================================
ynh_script_progression --message="Building Movim..."

# Install composer
ynh_install_composer

# hack to make composer use php8.2 rather than system-default 7.4
ln -s $(which php$phpversion) $install_dir/php
PATH=$install_dir:$PATH

ynh_exec_warn_less ynh_composer_execute --commands="movim:migrate"
rm $install_dir/php
ynh_exec_as "$app" "php$phpversion" "$install_dir/daemon.php" config --username="$admin" --password="$password" --quiet

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --usage=$fpm_usage --footprint=$fpm_footprint

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated systemd config
ynh_add_systemd_config
yunohost service add "$app" --description="Responsive web-based XMPP client"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..."

# Start a systemd service
ynh_systemd_action --service_name="$app" --action="start" --log_path="systemd" --line_match="Movim daemon launched"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
