#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
final_path=$(ynh_app_setting_get "$app" final_path)

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

# Remove the dedicated nginx config
ynh_secure_remove "/etc/nginx/conf.d/${domain}.d/movim.conf"

#=================================================
# REMOVE PHP-FPM CONFIGURATION
#=================================================

# Remove the dedicated php-fpm config
ynh_secure_remove "/etc/php5/fpm/pool.d/movim.conf"

# Reload services
service nginx reload
service php5-fpm restart

#=================================================
# STOP AND REMOVE SERVICE
#=================================================

service movim stop
if [ -d /run/systemd/system ]; then
    systemctl --quiet disable movim.service
    ynh_secure_remove /lib/systemd/system/movim.service
    systemctl --quiet daemon-reload
else
    update-rc.d -f movim remove
    ynh_secure_remove /etc/init.d/movim
fi

#=================================================
# REMOVE DEPENDENCIES
#=================================================

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE THE MYSQL DATABASE
#=================================================

db_user=movim
db_name=movim
ynh_mysql_drop_db "$db_name" || true
ynh_mysql_drop_user "$db_user" || true

#=================================================
# REMOVE APP MAIN DIR
#=================================================

ynh_secure_remove "$final_path"

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================

ynh_system_user_exists movim \
  && userdel movim
