#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=100M

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if [ -f "$install_dir/config/db.inc.php" ]; then
    ynh_safe_rm "$install_dir/config/db.inc.php"
fi

if [[ -n "${path:-}" ]] && [[ "${path:-}" != "/" ]]; then
    ynh_die "Movim can't be installed in a subdir anymore. Please change_url to the root of a domain before upgrading."
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env"

# Patch call to php in composer
ynh_replace -f "$install_dir/composer.json" --match='"vendor/bin/phinx' --replace='"@php vendor/bin/phinx'

# Patch call to php in daemon code
ynh_replace -f "$install_dir/src/Movim/Daemon/Session.php" --match="exec php" --replace="exec php$php_version"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration file..."

ynh_config_add --template="dot_env" --destination="$install_dir/.env"

#=================================================
# BUILD MOVIM
#=================================================
ynh_script_progression "Building $app..."

ynh_composer_install
ynh_composer_exec install --no-dev

COMPOSER_ALLOW_SUPERUSER=1 ynh_composer_exec config --global discard-changes true --quiet
COMPOSER_ALLOW_SUPERUSER=1 ynh_composer_exec update --no-interaction --quiet
COMPOSER_ALLOW_SUPERUSER=1 ynh_composer_exec movim:migrate --quiet

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Responsive web-based XMPP client"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Movim daemon launched"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
